### ISSUE TITLE
CustomCompactLSTMBuilder is super-slow

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#177]
This change caused a 20-fold accuracy drop on GPU (confirmed by both me and @philip30):
https://github.com/neulab/xnmt/commit/e75b54894c74b210b8c49bde082a6ab2e6eaf8af#diff-d5c251b1ac3d0ca2da44bf734613b4c9L86

Could you take a look and fix/revert it?

**Comment by msperber** [comment]
That should probably be fixed with #175 
There was some weirdness going on that caused the LSTM inputs to be picked into many tiny expressions of size 1.

**Comment by philip30** [comment]
Can you somehow check that? Where is the actual fix in the PR?

**Comment by msperber** [comment]
It's this line: https://github.com/neulab/xnmt/pull/175/files#diff-dbefd133021db530b87ac21a33ec8a82R124

The previous typecheck didn't catch dy._lookup_Expression, and then calling list(look_expression) apparently picked it into tiny expressions. I've been running this branch on GPU and haven't noticed any speed issues, that's why I think this should fix it!

**Comment by philip30** [comment]
I am going to try this branch on my dataset, hold on a second.

**Comment by philip30** [comment]
I confirmed a 30x speed improvement from yesterday :)

**Comment by philip30** [comment]
I think this issue can be closed if the PR is merged to the master, @neubig.

**Comment by neubig** [comment]
I was having trouble running the unit tests due to a path issue in Python 3. Once this is resolved it's OK to merge this PR I think.
