### ISSUE TITLE
masking not implemented correctly with initialization in lstm.py 

### ISSUE THREAD

**Issue by cindyxinyiwang** [neulab/xnmt#223]
in lstm.py, the customLSTMbuilder uses the class LSTMState. When you call add_input, you just pass in previous state. However, if you call a customLSTMbuilder with initial_state, it returns a LSTM state with some initialized c and h value. But this initial state does not have a previous_state property. So when you call add_input to it, it would not pass in the initialized c and h, and this initialization information would be lost forever?

**Comment by neubig** [comment]
Hmm, this sounds bad. @msperber may not be around this week, but if you could push a proposed fix I'll take a look.

**Comment by neubig** [comment]
OK, there are several issues here (pointed out by @cindyxinyiwang):

1. In `lstm.py` line 82 to 84, there is a add_input function, which only passes in previous state and input. This is used in line 156, the `CustomLSTMBuilder.add_input`. However, on line 137, when we initialize a LSTM state, we just set `c` and `h`, not prev_state. Which means that it would pass None when you call `add_input` for the first time.

2. The ordering of `c` and `h` is inconsistent with DyNet's ordering. DyNet puts `c` first, while `lstm.py` puts `h` first. This should probably be fixed.

3. CustomCompactLSTMBuilder is used by default. It seems to me that VanillaLSTMBuilder (or maybe CompactVanillaLSTMBuilder) should be used by default, maybe with an option to use the custom one. This is mostly just because I trust VanillaLSTMBuilder to be correct, but other ones maybe less so.

I started fixing some stuff, but ran out of time tonight. I think https://github.com/neulab/xnmt/issues/224 is more urgent, so I may work on it next.

**Comment by msperber** [comment]
It seems the problematic code is currently not used anywhere. The decoder uses dy.CompactVanillaLSTMBuilder, and in the encoder add_input() is never used. For that matter, the XNMT custom code does not even support set_s() which is required by the decoder. To avoid confusion, we might just remove the problematic code for now and treat the custom LSTM purely as a SeqTransducer, not an RNNBuilder? There is probably no advantage of using the custom LSTM in the decoder currently unless people need the flexibility to change the decoder LSTM code.

**Comment by neubig** [comment]
@msperber Yes, I agree that's probably be the best way to handle this.
