### ISSUE TITLE
Example model is not verbose enough

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#279]
Currently in `standard.yaml`, etc., the model file is now very very concise to the point that it is not necessarily a good example because it doesn't demonstrate any of the modifiable parameters. I think it'd be nice if we at least kept around the main elements of the MT system in the yaml file.

**Comment by mbollmann** [comment]
About the example files -- I thought many of them were very useful, but the main things I was missing (but have since figured out) were:

- Beam search decoding!  None of the example files show how to use it, though it is a very important feature, I would think.
- Early stopping.  The `08_multi_task.yaml` mentions early stopping (and learning rate decay) in the comments, but it isn't shown anywhere.

I realize the examples & docs are far from complete, but maybe this is useful for deciding what to add next!

**Comment by msperber** [comment]
An example of loading a model for the purpose of evaluation should also be added.

**Comment by neubig** [comment]
Fixed by #305
