### ISSUE TITLE
Separate the MlpSoftmaxDecoder's components

### ISSUE THREAD

**Issue by mbollmann** [neulab/xnmt#289]
I wondered how difficult it would be to separate the LSTM and MLP components of `MlpSoftmaxDecoder`.  My motivation for this is setting up multi-task experiments where the tasks share the decoder LSTM, but not the MLP.

At first I tried to just implement a quick hack for myself, but it turned out to be trickier than I thought.  Therefore, I wanted to ask for opinions and if there's interest to do this "the proper way". Particularly:

1. Could the LSTM and MLP parts of `MlpSoftmaxDecoder` just be encapsulated in their own serializable objects, which then become attributes of the decoder?
2. Couldn't the LSTM part of the decoder re-use `UniLSTMSeqTransducer`? It seems to me that the underlying model should be equivalent to what the decoder uses by default, but I don't know about all the implications for the implementation or serialization.
3. Do you think this would be a difficult change to make, or do you maybe have suggestions for a temporary workaround I could use?

Thanks for any input!

**Comment by msperber** [comment]
Yes, this would definitely be a good idea and in the spirit of XNMT. It shouldn't be hard to do, either. You would basically replace ```rnn_spec```, ```residual_to_output```,``` layers```, etc. by a single rnn argument, which could be set to any RNN builder, and the same for the MLP.

Note that it wouldn't be possible to pass ```dy.CompactVanillaLSTMBuilder``` as the RNN, because it is not serializable, and ```UniLSTMSeqTransducer``` is not usable as is because it can currently only transform a complete sequence, not step by step. The cleanest solution would be to implement ```initial_state()``` and ```add_input()``` for ```UniLSTMSeqTransducer```, similar as it is done in residual.py. A slightly faster way would be to make a shallow wrapper for ```dy.CompactVanillaLSTMBuilder``` that basically passes on all method calls to the dynet builder, and only adds Serializable as a base class.

One slight complication might be setting defaults for the rnn and mlp, because some arguments depend on whether or not input feeding is used, so the normal get_shared_params() mechanism probably won't suffice. I think it'd be worth to ignore that for now (meaning we would require to specify rnn and mlp explicitly in the config file as a first approximation), and think of a solution later.

Hope that helps! Feel free to post a [WIP] PR if you get stuck so I can take a look.

**Comment by mbollmann** [comment]
I am looking into this right now, and noticed that `UniLSTMSeqTransducer` is always a single layer only. This is kind of unintuitive, as it's different from `BiLSTMSeqTransducer` which *does* encapsulate multiple layers.

Is there a specific reason for this? It seems to make things more complicated for using `UniLSTMSeqTransducer` as a decoder component.

**Comment by msperber** [comment]
There's no specific reason other than multiple layers were not needed in the encoder because the bidirectional encoder could take care of that. Maybe the easiest way to fix it would be renaming ```UniLSTMSeqTransducer``` into ```LSTMLayer```, and then adding a new ```UniLSTMSeqTransducer``` that works the same as ```BiLSTMSeqTransducer``` except it uses only one direction per layer? If the interface between the old and new ```UniLSTMSeqTransducer``` is the same except for the number of layers which defaults to 1, then this would be an unintrusive change.

If it's easier, you can also directly extend ```UniLSTMSeqTransducer``` to support multiple layers.

**Comment by mbollmann** [comment]
Extending `UniLSTMSeqTransducer` seems like the easiest option to me. There's also no theoretical reason why you shouldn't be able to use a stack of uni-directional LSTMs as the encoder if you wanted to, right?

Am I right in assuming I can't just get a `dy.RNNState` object to return, but would have to implement a `PseudoState` object similar to the one used by the residual RNN code?

**Comment by msperber** [comment]
I'm not super familiar with the RNN states but yeah, you might have to implement something like ```PseudoState```. And yes, you could also use a unidirectional stack as the encoder (technically that's already possible using the ```ModularSeqTransducer``` with several one-layer modules, but that's not very convenient).

**Comment by mbollmann** [comment]
Sorry to be a bother, but the more I look at the code the more confused I get ...

I was thinking that implementing a state object for `UniLSTMSeqTransducer` would mean just duplicating a lot (or all?) of the functionality that `dy.RNNState` already provides, so I was looking into the `xnmt.residual.PseudoState` to see how it's done there. However, I don't see how this object achieves what it advertises, since it effectively doesn't keep any state at all.

It implements `add_input`, which should add an input to the current state (correct me if I'm wrong), by calling `ResidualRNNBuilder.transduce`, which in turn calls `UniLSTMSeqTransducer.__call__` (on its individual builder layers). That, however, always [starts from a zero state](https://github.com/neulab/xnmt/blob/master/xnmt/lstm.py#L91), so `add_input` doesn't really add any input at all, but always starts transducing from a clean slate... isn't that wrong? Does that not matter here? Am I missing something?

Feel free to open another issue for this if this strays too far from the original topic, but I feel I need to understand what the existing code is doing to implement these new features.

**Comment by msperber** [comment]
I agree that looks like a problem. I'm not sure what exactly the reason was for implementing the ```PseudoState```, maybe it was just to make some interface requirements happy but without adding the correct functionality. So it's probably a good idea to replicate the ```dy.RNNState functionality``` and not bothering about the ```PseudoState```.

**Comment by mbollmann** [comment]
I'm currently trying to wrap my head around this: `UniLSTMSeqTransducer.__call__` also contains batching code -- when initializing the hidden states (`dy.zeros(..., batch_size=batch_size)`), and also when updating them, by multiplying them with a mask.

Do I need to consider these things when implementing `initial_state` and `add_input`? Or can I assume that `add_input` only ever gets a single sample, and not a batched input?

**Comment by msperber** [comment]
I'm not sure if I understand your question correctly, but ```initial_state``` and ```add_input``` do need to accept batched inputs, although it's likely that you don't have to consider that in your code explicitly because DyNet hides the batching as much as possible.

**Comment by mbollmann** [comment]
My question is if I need to supply `dy.zeroes()` with a `batch_size` argument and if I need to consider masking in `add_input`, because both of these are done in `UniLSTMSeqTransducer.__call__`, but I don't really see how they would be transferred when working with `initial_state` and `add_input`.

**Comment by msperber** [comment]
I don't think masking needs to be considered in ```add_input```, it's only needed for bidirectional LSTMs for which we wouldn't use ```add_input``` anyways.

Regarding initializing with zeroes, this does need to consider the batch size, because ```vanilla_lstm_gates_dropout_concat``` does not do implicit broadcasting and would complain about mismatching batch size otherwise. If you don't know the batch size at this time, you might initialize the state to a batch size of 1, but then broadcast to the proper batch size when ```add_input``` is called and batch sizes don't fit. I don't think DyNet has a broadcast operator, but you can just add another zero vector of the proper batch size.

**Comment by mbollmann** [comment]
Hmm, setting a batch size in the `01_standard.yaml` example doesn't produce any such errors, though, although the code in #298 currently ignores batch size...

**Comment by msperber** [comment]
solved by #298
