### ISSUE TITLE
Exhaustive type annotation

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#438]
One of the problems I currently perceive with xnmt is that it's not clear what the inputs and outputs of each function are supposed to be. This is important because xnmt is a relatively big project written in a modular, object-oriented way that should enforce this. I think we should aim for exhaustive type annotation if possible to make this more clear.

One way to do so would be using mypy, and PyAnnotate:
> http://mypy-lang.org
> https://github.com/dropbox/pyannotate

I've tried mypy out and it looks good, although it's not clear whether it plays well with other external libraries.

We should probably also add type annotation to the programming style guide:
http://xnmt.readthedocs.io/en/latest/programming_style.html

**Comment by msperber** [comment]
Yeah, I think using those tools would be a good idea. This would basically be a one-time undertaking, right?

One potential difficulty we might face is circular imports, because type annotations requires importing the respective types. I have some ideas about this which I'll put in a separate issue.

**Comment by neubig** [comment]
Yes, this would be a one-time thing. And thanks!
