### ISSUE TITLE
When using LoadSerialized, easy way to re-initialize parameters

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#451]
@msperber I was wondering: when using LoadSerialized, is there an easy way to re-initialize some subset of the parameters to random values? For example, reset the word embeddings to random?

If not, this might be a good feature to have.

**Comment by msperber** [comment]
It should be possible (though not super convenient) by making a copy of the model and deleting the file corresponding to the subcollection of that component.

To come up with a more convenient interface, this should probably be considered together with #385.

**Comment by neubig** [comment]
Thanks! This seems to have worked. However, along with resetting the word embeddings, I'm also looking to reset the Vocab of the (source) word embedder. I tried adding this to the LoadSerialized file:

    - path: model.src_embedder.vocab
      val: !Vocab
        vocab_file: 'my_new_vocab.txt'

but this doesn't seem to overwrite the vocabulary and get the desired effect. I'm not super-familiar with the serializer, but I think this should work out-of-the-box. Do you think there's a reason why this shouldn't theoretically work? Or should I suspect a bug?

**Comment by msperber** [comment]
I can't think of a reason why this shouldn't work.. One starting place for debugging would be running in debug mode and looking at the dump of the model hierarchy.

Would it also be an option to just overwrite the whole embedder with a new one?

On a related note, it might be worth thinking about how to make (de)serialization more transparent. In my experience configuration is very convenient most of the time, but when something doesn't work it's hard to debug because the persistence code is quite complex..

**Comment by neubig** [comment]
Actually, the above turned out to be a mistake on my end. I had mis-written the path to something non-existant so it ended up not overwriting the vocabulary and just doing nothing. That being said, it seems like maybe an error or warning should be thrown when this happens, but this is perhaps a separate issue.
