### ISSUE TITLE
Ensembling several adapted systems doesn't work

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#461]
xnmt requires that all parameter sub-collections have unique names, which is true when ensembling as well. We get around this by ensuring that when parameters are initialized, they are given a unique name with a short hash that should very seldom collide with the hash generated by other models.

However, there is a problem when ensembling multiple models that have been adapted from the same model. For example:

    Train model 1
    Adapt model 2, starting from model 1
    Adapt model 3, starting from model 1
    Ensemble 2 and 3

Because both models start from model 1, they have identical names for all of the components. It'd be nice if there was a way that we could do ensembling without worrying about cross-model collisions at all. For example, could each model also be given a unique hash as well? Is there a way to do this already?

**Comment by msperber** [comment]
There's already a work-around to the related problem of checkpoint ensembling by @mbollmann, see xnmt/script/code/conv_checkpoints_to_model.py
I suppose it could be easily extended to rename the components of any given model, not just it's older checkpoints.

One possible option to get rid of this problem would be to rename components every time things are saved, but this would require some refactoring because we're currently reverting the saved parameters (but not the model file) to the best checkpoint some times during the training.

Alternatively, we could automatically or optionally make a copy+renaming when using !LoadSerialized?

For the idea with a unique hash for the whole model, I guess I don't fully understand how that would be incorporated and how to refer to it when loading a model.

**Comment by neubig** [comment]
Okay, thanks a lot. For the time being I'll use that script. In the long
term I think optionally renaming the hashes on loading would be a good work
around probably.

Graham

-- Sent from my phone so apologies for brevity and typos.
