### ISSUE TITLE
No more batched decoding for DefaultTranslator

### ISSUE THREAD

**Issue by pierregodard** [neulab/xnmt#481]
PR #445 introduced an [exception](https://github.com/neulab/xnmt/blob/master/xnmt/translator.py#L183) for batch sizes larger than 1. Was there a bug prior to this PR, or is this a regression due to refactoring?
Thank you!

**Comment by msperber** [comment]
This is neither a regression nor a prior bug. The PR had improved consistency in some places, including that we always use an inference batcher (```InOrderBatcher``` of batch size 1 by default), and that we always pass batches of things to ```generate()``` and ```calc_loss()```. Previously, when a batch of size > 1 was passed, ```generate()``` would simply loop over each batch element, which was a bit misleading and added some unnecessary code, which is why it is now removed.

**Comment by pierregodard** [comment]
Thanks a lot @msperber for the clarification. I got worried batching during training was gone for DefaultTranslator, as a previously working config file with a batch size > 1 stopped working, but I now understand it was silly of me to re-use the training batch size for the inference batcher in that config file. Apologies for the disturbance.

**Comment by msperber** [comment]
Sure, no worries!
