### ISSUE TITLE
API doc is broken

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#487]
http://xnmt.readthedocs.io/en/latest/api_doc.html

**Comment by msperber** [comment]
Hm these things have been hard to catch because (1) Sphinx only raises warnings but does not stop the build, and (2) things usually build fine on my Mac but not on RTD.

I just fixed one issue, but now we're getting a different error that seems to be due to a bug in Sphinx: https://github.com/sphinx-doc/sphinx/issues/5291
