### ISSUE TITLE
deepcopy causes memory copy

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#498]
Currently on this line     new_sent = copy.deepcopy(self)

deepcopy is causing a memory copy and crashes. I tried to implement a fix that only deepcopies the relevant words, but for some reason this is not working. Are there any ideas?

**Comment by philip30** [comment]
Yep, maybe we can make SegmentedSentence avoid this. I'd suggest not to reconstruct input many times though, if we can just simply modify the field. So __class__() or copy() shouldn't be called.

**Comment by msperber** [comment]
Hm, ```Sentence``` is currently designed as an immutable class which is usually a good way to prevent bugs, and this is mainly needed for batching (max once per epoch), so I think unless we experience performance issues somewhere it's fine to return a new object..

**Comment by philip30** [comment]
I actually do modify the sentence in the older version to simplify the implementation of attention report for segmented input. but yeah, maybe we should be really careful for the immutable attribute because it's useful.

When we reconstruct the input somewhere, maybe in batcher or somewhere else, we need to ensure that we are constructing the correct class with the correct argument. This is maybe the biggest challenge.

**Comment by neubig** [comment]
Thanks both! And thanks for dealing with this cryptic issue... I wrote it when I was half-falling-asleep and reading it when I woke up it doesn't make very much sense :)

Basically the problem is that deepcopy was copying a bunch of other things like the vocab and output_processors, and because this takes a lot of memory, this was causing crashes on any reasonably sized translation task.

**Comment by neubig** [comment]
It should be fixed by #499
