### ISSUE TITLE
Documentation of expected input/output of each function call for the upper-level abstract classes

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#55]
I think we should document the type of the expected input/output of each function call of the upper-level abstract classes to make sure that our API is clear. Here are the classes that need documentation:

- [ ] Action
- [ ] Attender
- [ ] Translator
- [ ] Output
- [ ] Decoder
- [ ] SearchStrategy
- [ ] Encoder
- [ ] Evaluator
- [ ] Input
- [ ] LengthNormalization
- [ ] Embedder
- [ ] Batcher

**Comment by neubig** [comment]
Let me re-state that this is important. Because XNMT doesn't have command line arguments, it's often hard to see what we need to pass in to initialize each class. If we add docstrings, along with the type of input they expect, to all of the major classes, this will greatly help newcomers understand what they need to pass in in their YAML files.

**Comment by msperber** [comment]
I can get started with documenting some of the parts I'm familiar with. Would it be okay to switch to the Google-style docstring, same as DyNet? I find it much more readable, and less likely to forget documenting changes in the API. It'll only require the [napolean sphinx plugin](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/), and will still support docstrings in the old format while transitioning.

**Comment by neubig** [comment]
I found the Google-style docstring more verbose, but if you think that's better I'd be OK with changing.

**Comment by neubig** [comment]
(and thanks for offering to help!)

**Comment by msperber** [comment]
For some reason the readthedocs build failed: http://readthedocs.org/projects/xnmt/builds/6877250/
Sphinx is working fine on my local machine.

**Comment by neubig** [comment]
Here is a list of commands that you can run to debug: http://readthedocs.org/projects/xnmt/builds/6877250/

**Comment by msperber** [comment]
The problem seems to be that the xnmt package contains subpackages such as xnmt.serialize, which RTD is not importing properly. The documentation suggests to "Install your project inside a virtualenv using ``setup.py install``": http://docs.readthedocs.io/en/latest/faq.html#can-i-document-a-python-package-that-is-not-at-the-root-of-my-repository

Could you take a look at that option @neubig ?

By the way, the above link points to an outdated RTD built. The most recent one is http://readthedocs.org/projects/xnmt/builds/6991215/ and it's not marked as failing, but the sphinx command prints a lot of failed imports leading to empty doc pages.

**Comment by neubig** [comment]
Will be subsumed by https://github.com/neulab/xnmt/issues/438
