### ISSUE TITLE
Translator touching internals of DecoderState

### ISSUE THREAD

**Issue by armatthews** [neulab/xnmt#554]
Right now the translator class assumes the use of AutoRegressiveDecoder and directly uses dec_state.rnn_state and dec_state.context.

I propose that we refactor this to have a DecoderState class, of which AutoRegressiveDecoderState is a subclass. The DecoderState class would have a method called as_vector(), which for AutoRegressiveDecoderState simply returns self.rnn_state.output(). The context vector should probably not be stored in the DecoderState at all, but instead be passed into decoder.calc_loss separately.

**Comment by msperber** [comment]
```truncate_dec_batches``` assumes that sentences within the minibatch are sorted by target length, and truncates batch elements for sentences that are complete (rather than appending a series of padding tokens and masking away the loss). This is mainly a memory optimization e.g. for character-level decoders. If you find it difficult to work around it, I think it could be discussed to remove this feature, as it's a bit against XNMT spirit (introducing moderate computational optimizations at the cost of increased code complexity), and I actually haven't used it so far, despite being the person who implemented it..

**Comment by armatthews** [comment]
I agree that such things are against the spirit of XNMT, which should be to make things as easily extensible as possible. If you're not using this then I'll remove this bit and send a PR. We can think about how to re-add this in the future with a more modular design.
